### ISSUE TITLE
Keyboard displays wrong symbols on Linux (lubuntu)

### ISSUE THREAD

**Issue by OmriSoudry** [comtel2000/fx-experience#17]
i.e: instead of the Quit icon, it displays "2", instead of the Backspace icon, it displays "!"

**Comment by comtel2000** [comment]
I guess the ttf symbol font did not load correctly. Maybe there is a problem with lubuntu and truetype fonts and you have to change the symbol icons to svg..

**Comment by comtel2000** [comment]
still open?
