### ISSUE TITLE
Disable KeyBoard only for one input Text 

### ISSUE THREAD

**Issue by protid** [comtel2000/fx-experience#21]
Hello, i am using fx-onscreen-keyboard, i ve added like this:
`
popupKey = KeyBoardPopupBuilder.create().initLocale(Locale.FRENCH).build();
popupKey.addFocusListener(scene, true);
`

Is there a way to disable it only for a specific TextField ?

**Comment by comtel2000** [comment]
It's only possible by not using the global listener registration and add the keyboard listener manually for selected textfields. Sounds like a new feature for the vk properties.

**Comment by comtel2000** [comment]
fixed in v11.0.0 by add a vkState property with value on/off - see sample package
