### ISSUE TITLE
Is there a way to fix the position of keyboard popup?

### ISSUE THREAD

**Issue by graynk** [comtel2000/fx-experience#24]
I want to replace default VK with this one on embedded device with touch screen. So I would like the same behavior: I want it the to be the same size and to popup at the bottom of the screen. I've tried using popup.setOnShown method with setX and setY, and it works for text keyboard, but for numeric fields it creates the popup near the field, and this breaks it for later usage on text fields as well. Is there a way to fix the location of the popup?

**Comment by comtel2000** [comment]
I'm not sure what you looking for. The default positioning is based on the focused text component (lower left edge). For your own position logic you have to build your own focus listener or extend the [FXOK ](https://github.com/comtel2000/fx-experience/blob/master/fx-onscreen-keyboard/src/main/java/org/comtel2000/keyboard/FXOK.java) and change it to your lower screen coordinates.

**Comment by graynk** [comment]
I was wondering if there's a way to not position the popup based on the 
focused field, but to have it always appear in the same spot, like default 
virtual keyboard does: at the bottom on the screen. But I understood you, I 
need to implement that myself, thank you

**Comment by comtel2000** [comment]
just use a border layout on your scene for the fx keyboard pane at the bottom without popup and register a focus listener for show and hide. Sound much easier than using relative text field positioning.

**Comment by graynk** [comment]
Yeah, that makes sense, I'll try it, thanks
