### ISSUE TITLE
How to set size KeyboardPane?

### ISSUE THREAD

**Issue by duongxinh2003** [comtel2000/fx-experience#27]
I have an AnchorPane and I want to set KeyboardPane into this. But I saw the Keyboard layout covered full of AnchorPane but the buttons seem unchanged. Anyone can help me?
`@FXML`
  `public AnchorPane apKeyboard;`

  `@FXML`
  `public void btnShowKeyboardActionPerformed(ActionEvent actionEvent) throws Exception {`
    `KeyboardPane keyboardPane = new KeyboardPane();`
   `keyboardPane.setPrefSize(apKeyboard.getWidth(), apKeyboard.getHeight());`
    `keyboardPane.load();`
    `apKeyboard.getChildren().addAll(keyboardPane);`
  `}`
![image](https://user-images.githubusercontent.com/25058528/72661387-d2912400-3a0b-11ea-9290-6b1f6620a383.png)

**Comment by comtel2000** [comment]
The keyboard pane size is defined by the xml layout. Not sure why a additional anchorpane parent, but try to change the scale property of the keyboard

**Comment by comtel2000** [comment]
closed (out dated)
