### ISSUE TITLE
Add the possibility to set a widht / height to the keyboardpane

### ISSUE THREAD

**Issue by iXo** [comtel2000/fx-experience#4]
Hello, I ma using your keyboard (great stuff !) in a controlfx dialog, I made the dialog a little less bigger of my scene, but the keyboard doesn't follow the box size (and there seems to be a little bug for the surrounding border).

When I am using the zoom button, or the setscale method, I can zoom it to neraly the size I am want, but because my program can be run on different resolutions, I don't know how to compute the right setscale param.

Could there be a way to set the size of the keyboard, a maybe a vertical / horizontal grow mecanism ?

Thanks.

![Sample 1](http://www.kawaiyume.org/wp-content/uploads/2014/11/keyb1.png)
![Sample 2](http://www.kawaiyume.org/wp-content/uploads/2014/11/keyb2.png)

**Comment by comtel2000** [comment]
closed
